#!/usr/bin/env python3
"""Render gan-harness/build-report.md from the run's evidence at the verification closeout.

Grounded and never invents: the score progression comes from gan-harness/feedback/feedback-*.md,
the gates from approvals.json, and coverage from the deliverables/plan/tests on disk. Unknown
values are written as `TODO: Add details` rather than guessed. Per-iteration verdict is derived
deterministically from the score against the pass threshold.
"""
from __future__ import annotations

import argparse
import json
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FEEDBACK = ROOT / "gan-harness" / "feedback"
OUT = ROOT / "gan-harness" / "build-report.md"
DEFAULT_THRESHOLD = 7.0

DELIVERABLES = [
    ("Problem Statement", "output/PROBLEMSTATEMENT.md"),
    ("Design", "output/DESIGN.md"),
    ("Technical Gaps", "output/TechnicalGaps.md"),
    ("Implementation Plan", "output/IMPLEMENTATIONPLAN.md"),
]


def _read(rel_or_path) -> str:
    p = rel_or_path if isinstance(rel_or_path, Path) else ROOT / rel_or_path
    try:
        return p.read_text(encoding="utf-8")
    except OSError:
        return ""


def _score(text: str):
    m = re.search(r"(\d+(?:\.\d+)?)\s*/\s*10", text)
    return float(m.group(1)) if m else None


def _iterations() -> list[dict]:
    rows = []
    for f in sorted(FEEDBACK.glob("feedback-*.md")):
        n = re.search(r"(\d+)", f.name)
        rows.append({"iter": int(n.group(1)) if n else 0, "file": f.name, "score": _score(_read(f))})
    return rows


def _project_name() -> str:
    for rel in ("output/PROBLEMSTATEMENT.md", "output/DESIGN.md"):
        m = re.search(r"^#\s+(.+)$", _read(rel), re.M)
        if m:
            return re.sub(r"^(Problem Statement|Design)\s*[\u2014-]\s*", "", m.group(1)).strip()
    return "Project"


def _approvals() -> dict:
    try:
        return json.loads(_read("gan-harness/approvals.json") or "{}")
    except json.JSONDecodeError:
        return {}


def _gate_line(name: str, gate: dict | None) -> str:
    if not gate or not gate.get("approved"):
        return f"- {name} approval: **not approved**"
    return f"- {name} approval: **approved** by `{gate.get('by', '?')}`"


def _deliverables_done() -> tuple[int, int]:
    done = sum(1 for _, rel in DELIVERABLES if _read(rel).strip())
    return done, len(DELIVERABLES)


def _task_count() -> int:
    return len(re.findall(r"^\|\s*T-?\w*\d+\b", _read("output/IMPLEMENTATIONPLAN.md"), re.M))


def _test_count() -> tuple[int, int]:
    tests = ROOT / "tests"
    files = cases = 0
    for p in tests.rglob("*"):
        if not p.is_file() or "__pycache__" in p.parts:
            continue
        if re.fullmatch(r"test_.*\.py|.*_test\.py", p.name):
            files += 1
            cases += len(re.findall(r"^\s*(?:async\s+)?def\s+test_\w+", _read(p), re.M))
        elif re.search(r"\.(spec|test)\.(ts|tsx|js|jsx)$", p.name):
            files += 1
            cases += len(re.findall(r"\b(?:it|test)\s*\(\s*[`'\"]", _read(p)))
    return cases, files


def _verdict(score, threshold: float) -> str:
    if score is None:
        return "TODO"
    return "PASS" if score >= threshold else "ITERATE"


def render(threshold: float, verdict_override: str | None) -> str:
    name = _project_name()
    iters = _iterations()
    final = iters[-1]["score"] if iters else None
    verdict = verdict_override or _verdict(final, threshold)
    ap = _approvals()
    d_done, d_total = _deliverables_done()
    cases, t_files = _test_count()
    tasks = _task_count()

    out: list[str] = [
        f"# Build Report \u2014 {name}",
        "",
        f"> Generated by the verification closeout on {date.today().isoformat()} from the run's evidence",
        "> (feedback history, approvals, deliverables, tests). Do not hand-edit.",
        "",
        "## Summary",
        f"- Final verdict: {verdict}",
        f"- Final weighted score: {final if final is not None else 'TODO'} / 10",
        f"- Pass threshold: {threshold:g} / 10",
        f"- Iterations run: {len(iters) if iters else 'TODO'}",
        "",
        "## Score Progression",
    ]
    if iters:
        out += ["| Iteration | Weighted total | Verdict | Feedback |", "| --- | --- | --- | --- |"]
        for it in iters:
            s = it["score"]
            out.append(
                f"| {it['iter']:03d} | {s if s is not None else 'TODO'} | {_verdict(s, threshold)} | "
                f"[{it['file']}](feedback/{it['file']}) |"
            )
    else:
        out.append("_No feedback iterations recorded yet._")

    out += [
        "",
        "## Gates",
        _gate_line("Design", ap.get("design")),
        _gate_line("Plan", ap.get("plan")),
        "",
        "## Coverage",
        f"- Deliverables: {d_done}/{d_total} present",
        f"- Plan tasks: {tasks if tasks else 'TODO'}",
        f"- Tests: {cases} cases across {t_files} files",
        "",
        "## Outstanding Items",
        "- TODO: Add details \u2014 anything deferred, with rationale (see the latest feedback file).",
        "",
        "## Links",
        "- Plan: [IMPLEMENTATIONPLAN.md](../output/IMPLEMENTATIONPLAN.md)",
        "- Feedback history: [feedback/](feedback/)",
        "",
    ]
    return "\n".join(out)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Render gan-harness/build-report.md from run evidence.")
    parser.add_argument("--threshold", type=float, default=DEFAULT_THRESHOLD, help="pass threshold (default 7.0)")
    parser.add_argument("--verdict", choices=["PASS", "ITERATE"], default=None,
                        help="override; default derived from the final score vs threshold")
    parser.add_argument("--out", default=str(OUT))
    args = parser.parse_args(argv)
    Path(args.out).write_text(render(args.threshold, args.verdict), encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
