"""Sync + materialize durable memory into Copilot-readable instruction files.

Durable repo + pinned-global memory under ``.github/memory/**`` is materialized into committed
``.github/instructions/**`` (design memory-architecture.md §5.2, plan G2/G3) so VS Code Copilot
can read it. Output is path-scoped via ``applyTo`` and descriptor-dense (A9), deterministic,
and idempotent. If the global store is not pinned/available it degrades to repo scope (R2).
"""
import argparse
from datetime import date
from pathlib import Path

import yaml

CODE_SCOPE = "src/**,tests/**,scripts/**,infra/**"
REPO_SCOPE = CODE_SCOPE
GLOBAL_SCOPE = CODE_SCOPE
AUTOGEN_NOTE = "<!-- AUTO-GENERATED by .github/scripts/sync-memory.py — do not edit by hand. -->"
EMPTY_NOTE = "<!-- No memory records materialized yet. -->"
GLOBAL_UNAVAILABLE_NOTICE = "global store not pinned/available; repo-scope only"


def load_records(path: Path) -> list:
    doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if isinstance(doc, list):
        return doc
    if "id" in doc and "descriptor" in doc:
        return [doc]
    lists = [value for value in doc.values() if isinstance(value, list)]
    return lists[0] if lists else []


def is_materializable(record: dict) -> bool:
    privacy = record.get("privacy") or {}
    if privacy.get("classification") == "sensitive":
        return False
    if privacy.get("redacted") is False:
        return False
    return bool(record.get("descriptor"))


DEFAULT_POLICY = {"confidence_threshold": 0.65, "staleness_ttl_days": 30,
                  "max_recalled_entries": 5, "max_retrieved_memory_tokens": 8000,
                  "evict_after_unused_days": 90}


def _load_yaml(path: Path) -> dict:
    return (yaml.safe_load(path.read_text(encoding="utf-8")) if path.exists() else {}) or {}


def load_policy(repo_root: Path) -> dict:
    return {**DEFAULT_POLICY, **_load_yaml(repo_root / ".github" / "memory" / "policy.yaml")}


def _clock(record: dict):
    # Freshness clock: last_confirmed (a used/re-verified rule) preferred over birth date.
    ev, life = record.get("evidence") or {}, record.get("lifecycle") or {}
    return _as_date(ev.get("last_confirmed") or life.get("created"))


def _fresh(record: dict, ttl_days: int) -> bool:
    life = record.get("lifecycle") or {}
    if life.get("status") in ("archived", "deprecated"):
        return False
    stamp = _clock(record)
    if stamp is None:
        return True
    return (date.today() - stamp).days <= (life.get("ttl_days") or ttl_days)


def _promotion_rank(record: dict) -> tuple:
    ev = record.get("evidence") or {}
    clock = _clock(record)
    return (record.get("confidence") or 0, ev.get("occurrences") or 0,
            clock.toordinal() if clock else 0)


def resolve_conflicts(records: list) -> list:
    """Promotion-time override: drop explicitly-superseded records, and among records that
    declare the same conflict_key keep only the strongest by (confidence, occurrences, recency)."""
    superseded = {r.get("supersedes") for r in records if r.get("supersedes")}
    winners, passthrough = {}, []
    for r in records:
        if r.get("id") in superseded:
            continue
        key = r.get("conflict_key")
        if key is None:
            passthrough.append(r)
        elif key not in winners or _promotion_rank(r) > _promotion_rank(winners[key]):
            winners[key] = r
    return passthrough + list(winners.values())


def _eligible(records: list, policy: dict) -> list:
    # Store membership implies promotion/verification; drop only deprecated/stale, sensitive,
    # and explicitly low-confidence records, then rank + cap downstream.
    thr = policy["confidence_threshold"]
    return [r for r in records if is_materializable(r) and _fresh(r, policy["staleness_ttl_days"])
            and (r.get("confidence") is None or r.get("confidence") >= thr)]


def _rank_cap(records: list, policy: dict) -> list:
    ranked = sorted(records, key=lambda r: (r.get("confidence") or 0), reverse=True)
    kept, used = [], 0
    for r in ranked[: policy["max_recalled_entries"]]:
        cost = len(r["descriptor"]) // 4 + 1
        if used + cost > policy["max_retrieved_memory_tokens"]:
            break
        used += cost
        kept.append(r)
    return kept


def _as_date(value):
    if isinstance(value, str):
        try:
            return date.fromisoformat(value)
        except ValueError:
            return None
    return value


def _evict_unused(records: list, policy: dict) -> list:
    # LRU: a record that WAS recalled (has last_used) but has gone cold past the window is evicted.
    window = policy.get("evict_after_unused_days")
    if not window:
        return records
    today = date.today()
    kept = []
    for r in records:
        used = _as_date((r.get("evidence") or {}).get("last_used"))
        if used is None or (today - used).days <= window:
            kept.append(r)
    return kept


def _promote(records: list, policy: dict) -> list:
    return _rank_cap(resolve_conflicts(_evict_unused(_eligible(records, policy), policy)), policy)


def dense_bullets(records: list, policy: dict) -> list:
    return [f"- {r['descriptor']}" for r in _promote(records, policy)]


def render_instruction_file(apply_to: str, records: list, policy: dict) -> str:
    bullets = dense_bullets(records, policy) or [EMPTY_NOTE]
    header = ["---", f'applyTo: "{apply_to}"', "---", "", AUTOGEN_NOTE, ""]
    return "\n".join(header + bullets) + "\n"


def load_lock(repo_root: Path) -> dict:
    return _load_yaml(repo_root / ".github" / "memory" / "global.lock")


def resolve_global_dir(repo_root: Path, override) -> Path | None:
    if override:
        path = Path(override)
        return path if path.is_dir() else None
    lock = load_lock(repo_root)
    if not lock.get("sha"):
        return None
    candidate = repo_root / lock.get("path", "")
    return candidate if candidate.is_dir() else None


def _records_from(paths: list) -> list:
    return [record for path in paths if path.exists() for record in load_records(path)]


def planned_files(repo_root: Path, global_override=None) -> tuple:
    policy = load_policy(repo_root)
    repo_dir = repo_root / ".github" / "memory" / "repo"
    repo_records = _records_from([repo_dir / "conventions.yaml", repo_dir / "style.yaml"])
    global_dir = resolve_global_dir(repo_root, global_override)
    global_paths = sorted(global_dir.glob("*.yaml")) if global_dir else []
    files = {
        "memory-repo.instructions.md": render_instruction_file(REPO_SCOPE, repo_records, policy),
        "memory-global.instructions.md": render_instruction_file(GLOBAL_SCOPE, _records_from(global_paths), policy),
    }
    return files, global_dir is None


def _targets(repo_root: Path, global_override) -> tuple:
    files, degraded = planned_files(repo_root, global_override)
    dest = repo_root / ".github" / "instructions"
    return [(dest / name, content) for name, content in files.items()], degraded


def materialize(repo_root: Path, global_override=None) -> list:
    targets, degraded = _targets(repo_root, global_override)
    for target, content in targets:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    return [GLOBAL_UNAVAILABLE_NOTICE] if degraded else []


def is_stale(repo_root: Path, global_override=None) -> bool:
    targets, _ = _targets(repo_root, global_override)
    return any(not t.exists() or t.read_text(encoding="utf-8") != c for t, c in targets)


def _repo_store_paths(repo_root: Path) -> list:
    repo_dir = repo_root / ".github" / "memory" / "repo"
    return [repo_dir / "conventions.yaml", repo_dir / "style.yaml"]


def _doc_list(doc):
    if isinstance(doc, dict):
        key = next((k for k, v in doc.items() if isinstance(v, list)), None)
        return key, (doc.get(key) or [])
    return None, (doc if isinstance(doc, list) else [])


def stamp_recall(repo_root: Path, used_ids, stamp: str) -> int:
    """Per-run recall proxy: write evidence.last_used=stamp for records whose id was recalled."""
    ids, total = set(used_ids), 0
    for path in _repo_store_paths(repo_root):
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) if path.exists() else None
        key, records = _doc_list(doc or {})
        hits = [r for r in records if isinstance(r, dict) and r.get("id") in ids]
        for r in hits:
            r.setdefault("evidence", {})["last_used"] = stamp
        if hits:
            payload = {key: records} if key else records
            path.write_text(yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8")
            total += len(hits)
    return total


def parse_args(argv):
    parser = argparse.ArgumentParser(description="Materialize memory into .github/instructions/**")
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--global-store", default=None)
    parser.add_argument("--check", action="store_true", help="report FRESH/STALE without writing")
    parser.add_argument("--stamp-recall", default=None,
                        help="stamp last_used=today on recalled records: 'auto' (all promoted) or a comma id list")
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    repo_root = Path(args.repo_root).resolve()
    if args.check:
        stale = is_stale(repo_root, args.global_store)
        print("STALE" if stale else "FRESH")
        return 1 if stale else 0
    if args.stamp_recall:
        auto = _promote(_records_from(_repo_store_paths(repo_root)), load_policy(repo_root))
        ids = [r.get("id") for r in auto] if args.stamp_recall == "auto" else args.stamp_recall.split(",")
        n = stamp_recall(repo_root, [i.strip() for i in ids if i and i.strip()], date.today().isoformat())
        print(f"Stamped last_used on {n} record(s)")
        return 0
    for notice in materialize(repo_root, args.global_store):
        print(notice)
    print("Materialized memory-repo.instructions.md and memory-global.instructions.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
